package main

// Builds a graph with all pokemon types and their relations
// (attacker / defender). The float32 weights represent the damage
// multiplier (super effective / not very effective / immune)
//
// Running this example will produce a big dot graph, that may not
// be the most meaningful to view.
//
// Filtering by the weights may provide less busy graphs for more insight:
//   - Getting super-effective damage relations:
//
//     cat << EOF | dot -Tpng -o test.png
//     digraph {
//       $(go run examples/pokemon-types/pokemontypes.go | grep '=2')
//     }
//     EOF
//
//
//   - Getting not-very-effective damage relations:
//
//     cat << EOF | dot -Tpng -o test.png
//     digraph {
//       $(go run examples/pokemon-types/pokemontypes.go | grep '=0.5')
//     }
//     EOF
//

import (
	"fmt"

	"github.com/zalgonoise/x/graph"
	"github.com/zalgonoise/x/graph/options"
)

var (
	normal   = graph.New[string, float32]("normal", "normal")
	fire     = graph.New[string, float32]("fire", "fire")
	fighting = graph.New[string, float32]("fighting", "fighting")
	water    = graph.New[string, float32]("water", "water")
	flying   = graph.New[string, float32]("flying", "flying")
	grass    = graph.New[string, float32]("grass", "grass")
	poison   = graph.New[string, float32]("poison", "poison")
	electric = graph.New[string, float32]("electric", "electric")
	ground   = graph.New[string, float32]("ground", "ground")
	psychic  = graph.New[string, float32]("psychic", "psychic")
	rock     = graph.New[string, float32]("rock", "rock")
	ice      = graph.New[string, float32]("ice", "ice")
	bug      = graph.New[string, float32]("bug", "bug")
	dragon   = graph.New[string, float32]("dragon", "dragon")
	ghost    = graph.New[string, float32]("ghost", "ghost")
	dark     = graph.New[string, float32]("dark", "dark")
	steel    = graph.New[string, float32]("steel", "steel")
	fairy    = graph.New[string, float32]("fairy", "fairy")
)

func main() {
	pokeTypeGraph := graph.New[string, float32]("pokemon-types", options.NoType, options.LabelWeight)

	pokeTypeGraph.Add(
		normal, fire, fighting, water, flying, grass, poison, ground,
		psychic, rock, ice, bug, dragon, ghost, dark, steel, fairy,
	)

	// normal
	pokeTypeGraph.Connect(normal.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), rock.ID(), 0.5)
	pokeTypeGraph.Connect(normal.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), ghost.ID(), 0)
	pokeTypeGraph.Connect(normal.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(normal.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(normal.ID(), fairy.ID(), 1)

	// fighting
	pokeTypeGraph.Connect(fighting.ID(), normal.ID(), 2)
	pokeTypeGraph.Connect(fighting.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), flying.ID(), 0.5)
	pokeTypeGraph.Connect(fighting.ID(), poison.ID(), 0.5)
	pokeTypeGraph.Connect(fighting.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), rock.ID(), 2)
	pokeTypeGraph.Connect(fighting.ID(), bug.ID(), 0.5)
	pokeTypeGraph.Connect(fighting.ID(), ghost.ID(), 0)
	pokeTypeGraph.Connect(fighting.ID(), steel.ID(), 2)
	pokeTypeGraph.Connect(fighting.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), psychic.ID(), 0.5)
	pokeTypeGraph.Connect(fighting.ID(), ice.ID(), 2)
	pokeTypeGraph.Connect(fighting.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(fighting.ID(), dark.ID(), 2)
	pokeTypeGraph.Connect(fighting.ID(), fairy.ID(), 0.5)

	// flying
	pokeTypeGraph.Connect(flying.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), fighting.ID(), 2)
	pokeTypeGraph.Connect(flying.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), rock.ID(), 0.5)
	pokeTypeGraph.Connect(flying.ID(), bug.ID(), 2)
	pokeTypeGraph.Connect(flying.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(flying.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), grass.ID(), 2)
	pokeTypeGraph.Connect(flying.ID(), electric.ID(), 0.5)
	pokeTypeGraph.Connect(flying.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(flying.ID(), fairy.ID(), 1)

	// poison
	pokeTypeGraph.Connect(poison.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), poison.ID(), 0.5)
	pokeTypeGraph.Connect(poison.ID(), ground.ID(), 0.5)
	pokeTypeGraph.Connect(poison.ID(), rock.ID(), 0.5)
	pokeTypeGraph.Connect(poison.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), ghost.ID(), 0.5)
	pokeTypeGraph.Connect(poison.ID(), steel.ID(), 0)
	pokeTypeGraph.Connect(poison.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), grass.ID(), 2)
	pokeTypeGraph.Connect(poison.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(poison.ID(), fairy.ID(), 2)

	// ground
	pokeTypeGraph.Connect(ground.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), flying.ID(), 0.5)
	pokeTypeGraph.Connect(ground.ID(), poison.ID(), 2)
	pokeTypeGraph.Connect(ground.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), rock.ID(), 2)
	pokeTypeGraph.Connect(ground.ID(), bug.ID(), 0.5)
	pokeTypeGraph.Connect(ground.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), steel.ID(), 2)
	pokeTypeGraph.Connect(ground.ID(), fire.ID(), 2)
	pokeTypeGraph.Connect(ground.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), grass.ID(), 0.5)
	pokeTypeGraph.Connect(ground.ID(), electric.ID(), 2)
	pokeTypeGraph.Connect(ground.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(ground.ID(), fairy.ID(), 1)

	// rock
	pokeTypeGraph.Connect(rock.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), fighting.ID(), 0.5)
	pokeTypeGraph.Connect(rock.ID(), flying.ID(), 2)
	pokeTypeGraph.Connect(rock.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), ground.ID(), 0.5)
	pokeTypeGraph.Connect(rock.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), bug.ID(), 2)
	pokeTypeGraph.Connect(rock.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(rock.ID(), fire.ID(), 2)
	pokeTypeGraph.Connect(rock.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), ice.ID(), 2)
	pokeTypeGraph.Connect(rock.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(rock.ID(), fairy.ID(), 1)

	// bug
	pokeTypeGraph.Connect(bug.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), fighting.ID(), 0.5)
	pokeTypeGraph.Connect(bug.ID(), flying.ID(), 0.5)
	pokeTypeGraph.Connect(bug.ID(), poison.ID(), 0.5)
	pokeTypeGraph.Connect(bug.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), ghost.ID(), 0.5)
	pokeTypeGraph.Connect(bug.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(bug.ID(), fire.ID(), 0.5)
	pokeTypeGraph.Connect(bug.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), grass.ID(), 2)
	pokeTypeGraph.Connect(bug.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), psychic.ID(), 2)
	pokeTypeGraph.Connect(bug.ID(), ice.ID(), 2)
	pokeTypeGraph.Connect(bug.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(bug.ID(), dark.ID(), 2)
	pokeTypeGraph.Connect(bug.ID(), fairy.ID(), 0.5)

	// ghost
	pokeTypeGraph.Connect(ghost.ID(), normal.ID(), 0)
	pokeTypeGraph.Connect(ghost.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), ghost.ID(), 2)
	pokeTypeGraph.Connect(ghost.ID(), steel.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), psychic.ID(), 2)
	pokeTypeGraph.Connect(ghost.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(ghost.ID(), dark.ID(), 0.5)
	pokeTypeGraph.Connect(ghost.ID(), fairy.ID(), 1)

	// steel
	pokeTypeGraph.Connect(steel.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), rock.ID(), 2)
	pokeTypeGraph.Connect(steel.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(steel.ID(), fire.ID(), 0.5)
	pokeTypeGraph.Connect(steel.ID(), water.ID(), 0.5)
	pokeTypeGraph.Connect(steel.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), electric.ID(), 0.5)
	pokeTypeGraph.Connect(steel.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), ice.ID(), 2)
	pokeTypeGraph.Connect(steel.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(steel.ID(), fairy.ID(), 2)

	// fire
	pokeTypeGraph.Connect(fire.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), rock.ID(), 0.5)
	pokeTypeGraph.Connect(fire.ID(), bug.ID(), 2)
	pokeTypeGraph.Connect(fire.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), steel.ID(), 2)
	pokeTypeGraph.Connect(fire.ID(), fire.ID(), 0.5)
	pokeTypeGraph.Connect(fire.ID(), water.ID(), 0.5)
	pokeTypeGraph.Connect(fire.ID(), grass.ID(), 2)
	pokeTypeGraph.Connect(fire.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), ice.ID(), 2)
	pokeTypeGraph.Connect(fire.ID(), dragon.ID(), 0.5)
	pokeTypeGraph.Connect(fire.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(fire.ID(), fairy.ID(), 1)

	// water
	pokeTypeGraph.Connect(water.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), ground.ID(), 2)
	pokeTypeGraph.Connect(water.ID(), rock.ID(), 2)
	pokeTypeGraph.Connect(water.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), steel.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), fire.ID(), 2)
	pokeTypeGraph.Connect(water.ID(), water.ID(), 0.5)
	pokeTypeGraph.Connect(water.ID(), grass.ID(), 0.5)
	pokeTypeGraph.Connect(water.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), dragon.ID(), 0.5)
	pokeTypeGraph.Connect(water.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(water.ID(), fairy.ID(), 1)

	// grass
	pokeTypeGraph.Connect(grass.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), flying.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), poison.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), ground.ID(), 2)
	pokeTypeGraph.Connect(grass.ID(), rock.ID(), 2)
	pokeTypeGraph.Connect(grass.ID(), bug.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), fire.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), water.ID(), 2)
	pokeTypeGraph.Connect(grass.ID(), grass.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), dragon.ID(), 0.5)
	pokeTypeGraph.Connect(grass.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(grass.ID(), fairy.ID(), 1)

	// electric
	pokeTypeGraph.Connect(electric.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), flying.ID(), 2)
	pokeTypeGraph.Connect(electric.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), ground.ID(), 0)
	pokeTypeGraph.Connect(electric.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), steel.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), water.ID(), 2)
	pokeTypeGraph.Connect(electric.ID(), grass.ID(), 0.5)
	pokeTypeGraph.Connect(electric.ID(), electric.ID(), 0.5)
	pokeTypeGraph.Connect(electric.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), dragon.ID(), 0.5)
	pokeTypeGraph.Connect(electric.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(electric.ID(), fairy.ID(), 1)

	// psychic
	pokeTypeGraph.Connect(psychic.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), fighting.ID(), 2)
	pokeTypeGraph.Connect(psychic.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), poison.ID(), 2)
	pokeTypeGraph.Connect(psychic.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(psychic.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), psychic.ID(), 0.5)
	pokeTypeGraph.Connect(psychic.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(psychic.ID(), dark.ID(), 0)
	pokeTypeGraph.Connect(psychic.ID(), fairy.ID(), 1)

	// ice
	pokeTypeGraph.Connect(ice.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), flying.ID(), 2)
	pokeTypeGraph.Connect(ice.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), ground.ID(), 2)
	pokeTypeGraph.Connect(ice.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(ice.ID(), fire.ID(), 0.5)
	pokeTypeGraph.Connect(ice.ID(), water.ID(), 0.5)
	pokeTypeGraph.Connect(ice.ID(), grass.ID(), 2)
	pokeTypeGraph.Connect(ice.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), ice.ID(), 0.5)
	pokeTypeGraph.Connect(ice.ID(), dragon.ID(), 2)
	pokeTypeGraph.Connect(ice.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(ice.ID(), fairy.ID(), 1)

	// dragon
	pokeTypeGraph.Connect(dragon.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), fighting.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(dragon.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), dragon.ID(), 2)
	pokeTypeGraph.Connect(dragon.ID(), dark.ID(), 1)
	pokeTypeGraph.Connect(dragon.ID(), fairy.ID(), 0)

	// dark
	pokeTypeGraph.Connect(dark.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), fighting.ID(), 0.5)
	pokeTypeGraph.Connect(dark.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), poison.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), ghost.ID(), 2)
	pokeTypeGraph.Connect(dark.ID(), steel.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), fire.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), psychic.ID(), 2)
	pokeTypeGraph.Connect(dark.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), dragon.ID(), 1)
	pokeTypeGraph.Connect(dark.ID(), dark.ID(), 0.5)
	pokeTypeGraph.Connect(dark.ID(), fairy.ID(), 0.5)

	// fairy
	pokeTypeGraph.Connect(fairy.ID(), normal.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), fighting.ID(), 2)
	pokeTypeGraph.Connect(fairy.ID(), flying.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), poison.ID(), 0.5)
	pokeTypeGraph.Connect(fairy.ID(), ground.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), rock.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), bug.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), ghost.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), steel.ID(), 0.5)
	pokeTypeGraph.Connect(fairy.ID(), fire.ID(), 0.5)
	pokeTypeGraph.Connect(fairy.ID(), water.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), grass.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), electric.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), psychic.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), ice.ID(), 1)
	pokeTypeGraph.Connect(fairy.ID(), dragon.ID(), 2)
	pokeTypeGraph.Connect(fairy.ID(), dark.ID(), 2)
	pokeTypeGraph.Connect(fairy.ID(), fairy.ID(), 1)

	// print graph in dot format
	fmt.Println(pokeTypeGraph)
}
