global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'collide'
    scrape_interval: 500ms
    params:
      headers: [ 'Accept: application/openmetrics-text' ]
    static_configs:
      - targets: ['collide:8080']

