# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: Mimir
    orgId: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true

datasources:
  - name: "Mimir"
    type: "prometheus"
    uid: "Mimir"
    access: "proxy"
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: "http://mimir-lb:9009/prometheus"
    editable: true
    secureJsonData:
      httpHeaderValue1: "anonymous"
    jsonData:
      httpMethod: "POST"
      httpHeaderName1: "X-Scope-OrgID"
      alertmanagerUid: "alertmanager"
      prometheusType: "Mimir"
      prometheusVersion: "2.9.1"
      tlsSkipVerify: true
      timeout: 30
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: "Tempo"
          name: trace_id
  - name: "Mimir Alertmanager"
    uid: "AlertManager"
    type: alertmanager
    access: proxy
    orgId: 1
    url: http://mimir-lb:9009/
    version: 1
    editable: true
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      implementation: "cortex"
    secureJsonData:
      httpHeaderValue1: "anonymous"