apiVersion: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: Pyroscope
    access: proxy
    url: http://pyroscope:4040
    basicAuth: false
    editable: true
    jsonData:
      minStep: '15s'