services:
  collide:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: collide
    restart: unless-stopped
    volumes:
      - ./internal/tracks/tracks.yaml:/tracks.yaml:ro
    environment:
      COLLIDE_HTTP_PORT: 8083
      COLLIDE_TRACKS_PATH: /tracks.yaml
      COLLIDE_LOG_LEVEL: DEBUG
      COLLIDE_LOG_WITH_SOURCE: true
      COLLIDE_LOG_WITH_SPAN_ID: true
      COLLIDE_TRACING_URI: tempo:4317
      COLLIDE_METRICS_URI: collector:4318
    ports:
      - "8083:8083"
      - "8081:8081"
    command: "serve"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=collide,environment=demo,service=collide
    networks:
      app-runtime:

networks:
  app-runtime: