version: '3.7'
services:

  prom:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./provisioning/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=730d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
    networks:
      audionet:


  grafana:
    image: grafana/grafana
    user: "1001"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./provisioning/grafana/audio-dashboard:/etc/dashboards
      - grafana:/var/lib/grafana
    networks:
      audionet:


volumes:
  prometheus:
  grafana:

networks:
  audionet: