version: '3.7'
services:

  audio:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - X_AUDIO_DURATION=4h
      - X_AUDIO_OUTPUT_TYPE=prom
      - X_AUDIO_OUTPUT=:13088
      - X_AUDIO_MODE=combined
      - X_AUDIO_BUCKET_SIZE=64
      - X_AUDIO_BATCH=1
      - X_AUDIO_BATCH_SIZE=64
      - X_AUDIO_BATCH_FREQUENCY=200ms
    env_file:
      - "./.env"
    ports:
      - "13088:13088"
    networks:
      audionet:
  

networks:
  audionet: