version: '3.7'
services:

  audio:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: audio
    restart: unless-stopped
    environment:
      - X_AUDIO_TIMEOUT=4h
      - X_AUDIO_OUTPUT_TYPE=prom
      - X_AUDIO_OUTPUT_PATH=:13088
      - X_AUDIO_MODE=combined
    env_file:
      - "./.env"
    ports:
      - "13088:13088"
  
