version: '3.7'
services:

  audio:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: audio
    restart: unless-stopped
    environment:
      - X_AUDIO_TIMEOUT=4h
      - X_AUDIO_OUTPUT_TYPE=prom
      - X_AUDIO_OUTPUT_PATH=:13088
      - X_AUDIO_MODE=combined
    env_file:
      - "./.env"
    ports:
      - "13088:13088"
  
  prom:
    image: prom/prometheus
    container_name: prom
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - "./.env"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data: