version: '3.7'
services:

  audio:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - X_AUDIO_TIMEOUT=4h
      - X_AUDIO_OUTPUT_TYPE=prom
      - X_AUDIO_OUTPUT_PATH=:13088
      - X_AUDIO_MODE=combined
      - X_AUDIO_NUM_SPECTRUM_BUCKETS=64
    env_file:
      - "./.env"
    ports:
      - "13088:13088"
    networks:
      audionet:
  

networks:
  audionet: