global:
  scrape_interval:     500ms
  evaluation_interval: 500ms


scrape_configs:
  - job_name: 'exemplars'
    scrape_interval: 500ms
    params:
      headers: ['Accept: application/openmetrics-text']
    static_configs:
      - targets: ['exemplars:13090']


