version: '3.7'
services:

  ca:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["/app/authz", "ca"]
    container_name: authz-ca
    ports:
      - "8080:8080"
      - "8081:8081"

  authz-root:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["/app/authz", "authz"]
    container_name: authz-root
    depends_on:
      - ca
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      AUTHZ_TARGET_CA_URL: "authz-ca:8081"

  authz-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["/app/authz", "authz"]
    container_name: authz-service
    depends_on:
      - authz-root
    ports:
      - "8084:8080"
      - "8085:8081"
    environment:
      AUTHZ_TARGET_CA_URL: "authz-root:8081"