{
 "title": "Collide API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "List Districts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "ListDistricts Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(list_districts_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(list_districts_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(list_districts_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(list_districts_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(list_districts_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99"
      }
     ]
    }
   ]
  },
  {
   "title": "List Tracks by District",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "ListAllTracksByDistrict Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(list_all_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(list_all_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(list_all_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(list_all_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(list_all_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "ListDriftTracksByDistrict Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(list_drift_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(list_drift_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(list_drift_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(list_drift_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(list_drift_tracks_by_district_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99"
      }
     ]
    }
   ]
  },
  {
   "title": "Get Alternatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "GetAlternativesByDistrictAndTrack Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(get_alternatives_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(get_alternatives_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(get_alternatives_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(get_alternatives_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(get_alternatives_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "GetAlternativesByDistrictAndTrack Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(get_collisions_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(get_collisions_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(get_collisions_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(get_collisions_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(get_collisions_by_district_and_track_latency_seconds_bucket[$__rate_interval])))",
       "legendFormat": "P99"
      }
     ]
    }
   ]
  }
 ]
}