global:
  scrape_interval:     500ms
  evaluation_interval: 500ms
  external_labels:
    cluster: observability
    namespace: exemplars


remote_write:
  - url: http://mimir-lb:9009/api/v1/push
    headers:
      X-Scope-OrgID: "anonymous"
    send_exemplars: true
    send_native_histograms: true

scrape_configs:
  - job_name: 'exemplars'
    scrape_interval: 500ms
    params:
      headers: ['Accept: application/openmetrics-text']
    static_configs:
      - targets: ['exemplars:13090']


