// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: all.proto

package generic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_not_ok Status = 0
	Status_ok     Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "not_ok",
		1: "ok",
	}
	Status_value = map[string]int32{
		"not_ok": 0,
		"ok":     1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_all_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_all_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{0}
}

type Generic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoolField   bool             `protobuf:"varint,1,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	Unsigned_32 uint32           `protobuf:"varint,2,opt,name=unsigned_32,json=unsigned32,proto3" json:"unsigned_32,omitempty"`
	Unsigned_64 uint64           `protobuf:"varint,3,opt,name=unsigned_64,json=unsigned64,proto3" json:"unsigned_64,omitempty"`
	Signed_32   int32            `protobuf:"zigzag32,4,opt,name=signed_32,json=signed32,proto3" json:"signed_32,omitempty"`
	Signed_64   int64            `protobuf:"zigzag64,5,opt,name=signed_64,json=signed64,proto3" json:"signed_64,omitempty"`
	Int_32      int32            `protobuf:"varint,6,opt,name=int_32,json=int32,proto3" json:"int_32,omitempty"`
	Int_64      int64            `protobuf:"varint,7,opt,name=int_64,json=int64,proto3" json:"int_64,omitempty"`
	Fixed_32    uint32           `protobuf:"fixed32,8,opt,name=fixed_32,json=fixed32,proto3" json:"fixed_32,omitempty"`
	Fixed_64    uint64           `protobuf:"fixed64,9,opt,name=fixed_64,json=fixed64,proto3" json:"fixed_64,omitempty"`
	Sfixed_32   int32            `protobuf:"fixed32,10,opt,name=sfixed_32,json=sfixed32,proto3" json:"sfixed_32,omitempty"`
	Sfixed_64   int64            `protobuf:"fixed64,11,opt,name=sfixed_64,json=sfixed64,proto3" json:"sfixed_64,omitempty"`
	Float_32    float64          `protobuf:"fixed64,12,opt,name=float_32,json=float32,proto3" json:"float_32,omitempty"`
	Float_64    float32          `protobuf:"fixed32,13,opt,name=float_64,json=float64,proto3" json:"float_64,omitempty"`
	Varchar     string           `protobuf:"bytes,14,opt,name=varchar,proto3" json:"varchar,omitempty"`
	ByteSlice   []byte           `protobuf:"bytes,15,opt,name=byte_slice,json=byteSlice,proto3" json:"byte_slice,omitempty"`
	IntSlice    []uint64         `protobuf:"varint,16,rep,packed,name=int_slice,json=intSlice,proto3" json:"int_slice,omitempty"`
	EnumField   *Status          `protobuf:"varint,17,opt,name=enum_field,json=enumField,proto3,enum=generic.Status,oneof" json:"enum_field,omitempty"`
	InnerStruct []*Generic_Short `protobuf:"bytes,18,rep,name=inner_struct,json=innerStruct,proto3" json:"inner_struct,omitempty"`
}

func (x *Generic) Reset() {
	*x = Generic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Generic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generic) ProtoMessage() {}

func (x *Generic) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generic.ProtoReflect.Descriptor instead.
func (*Generic) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{0}
}

func (x *Generic) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *Generic) GetUnsigned_32() uint32 {
	if x != nil {
		return x.Unsigned_32
	}
	return 0
}

func (x *Generic) GetUnsigned_64() uint64 {
	if x != nil {
		return x.Unsigned_64
	}
	return 0
}

func (x *Generic) GetSigned_32() int32 {
	if x != nil {
		return x.Signed_32
	}
	return 0
}

func (x *Generic) GetSigned_64() int64 {
	if x != nil {
		return x.Signed_64
	}
	return 0
}

func (x *Generic) GetInt_32() int32 {
	if x != nil {
		return x.Int_32
	}
	return 0
}

func (x *Generic) GetInt_64() int64 {
	if x != nil {
		return x.Int_64
	}
	return 0
}

func (x *Generic) GetFixed_32() uint32 {
	if x != nil {
		return x.Fixed_32
	}
	return 0
}

func (x *Generic) GetFixed_64() uint64 {
	if x != nil {
		return x.Fixed_64
	}
	return 0
}

func (x *Generic) GetSfixed_32() int32 {
	if x != nil {
		return x.Sfixed_32
	}
	return 0
}

func (x *Generic) GetSfixed_64() int64 {
	if x != nil {
		return x.Sfixed_64
	}
	return 0
}

func (x *Generic) GetFloat_32() float64 {
	if x != nil {
		return x.Float_32
	}
	return 0
}

func (x *Generic) GetFloat_64() float32 {
	if x != nil {
		return x.Float_64
	}
	return 0
}

func (x *Generic) GetVarchar() string {
	if x != nil {
		return x.Varchar
	}
	return ""
}

func (x *Generic) GetByteSlice() []byte {
	if x != nil {
		return x.ByteSlice
	}
	return nil
}

func (x *Generic) GetIntSlice() []uint64 {
	if x != nil {
		return x.IntSlice
	}
	return nil
}

func (x *Generic) GetEnumField() Status {
	if x != nil && x.EnumField != nil {
		return *x.EnumField
	}
	return Status_not_ok
}

func (x *Generic) GetInnerStruct() []*Generic_Short {
	if x != nil {
		return x.InnerStruct
	}
	return nil
}

type Generic_Short struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Generic_Short) Reset() {
	*x = Generic_Short{}
	if protoimpl.UnsafeEnabled {
		mi := &file_all_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Generic_Short) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generic_Short) ProtoMessage() {}

func (x *Generic_Short) ProtoReflect() protoreflect.Message {
	mi := &file_all_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generic_Short.ProtoReflect.Descriptor instead.
func (*Generic_Short) Descriptor() ([]byte, []int) {
	return file_all_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Generic_Short) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Generic_Short) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_all_proto protoreflect.FileDescriptor

var file_all_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x22, 0xfc, 0x04, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x33, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x33, 0x32,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x36, 0x34, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x36,
	0x34, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x33, 0x32, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x11, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x33, 0x32, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x36, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x12, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x36, 0x34, 0x12, 0x15, 0x0a, 0x06, 0x69,
	0x6e, 0x74, 0x5f, 0x33, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x74,
	0x33, 0x32, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x5f, 0x36, 0x34, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x5f, 0x33, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x07, 0x52, 0x07, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x36, 0x34,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x33, 0x32, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0f, 0x52, 0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x36, 0x34, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x10, 0x52,
	0x08, 0x73, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x5f, 0x33, 0x32, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x33, 0x32, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x36, 0x34,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x63, 0x68, 0x61, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x61, 0x72, 0x63, 0x68, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x79, 0x74,
	0x65, 0x5f, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62,
	0x79, 0x74, 0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f,
	0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x10, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x69, 0x6e, 0x74,
	0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x69, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x09, 0x65, 0x6e,
	0x75, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x88, 0x01, 0x01, 0x12, 0x39, 0x0a, 0x0c, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x0b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x1a, 0x2d, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x2a, 0x1c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a,
	0x06, 0x6e, 0x6f, 0x74, 0x5f, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x6f, 0x6b, 0x10,
	0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_all_proto_rawDescOnce sync.Once
	file_all_proto_rawDescData = file_all_proto_rawDesc
)

func file_all_proto_rawDescGZIP() []byte {
	file_all_proto_rawDescOnce.Do(func() {
		file_all_proto_rawDescData = protoimpl.X.CompressGZIP(file_all_proto_rawDescData)
	})
	return file_all_proto_rawDescData
}

var file_all_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_all_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_all_proto_goTypes = []interface{}{
	(Status)(0),           // 0: generic.Status
	(*Generic)(nil),       // 1: generic.Generic
	(*Generic_Short)(nil), // 2: generic.Generic.Short
}
var file_all_proto_depIdxs = []int32{
	0, // 0: generic.Generic.enum_field:type_name -> generic.Status
	2, // 1: generic.Generic.inner_struct:type_name -> generic.Generic.Short
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_all_proto_init() }
func file_all_proto_init() {
	if File_all_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_all_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Generic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_all_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Generic_Short); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_all_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_all_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_all_proto_goTypes,
		DependencyIndexes: file_all_proto_depIdxs,
		EnumInfos:         file_all_proto_enumTypes,
		MessageInfos:      file_all_proto_msgTypes,
	}.Build()
	File_all_proto = out.File
	file_all_proto_rawDesc = nil
	file_all_proto_goTypes = nil
	file_all_proto_depIdxs = nil
}
