version: '3.7'
services:

  exemplars:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: exemplars
    environment:
      X_OBSERVABILITY_TRACER_URI: "tempo:4317"
      X_OBSERVABILITY_METRICS_URI: "collector:4318"
      X_OBSERVABILITY_DUR: "3m"
    ports:
      - "13090:13090"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        loki-external-labels: job=dockerlogs,environment=demo,service=exemplars
    networks:
      app-runtime:


networks:
  app-runtime:
