{
 "title": "Audio",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Peaks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peaks - 500ms - near-real-time",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "audio_peak_value{job=\"audio\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peaks - 500ms - relative",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "audio_peak_value{job=\"audio\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Peaks - 500ms - absolute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "audio_peak_value{job=\"audio\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Spectrum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Frequencies - 1s - P25 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, rate(audio_spectrum_value_bucket{job=\"audio\"}[$__rate_interval]))",
     "legendFormat": "{{frequency}}Hz"
    }
   ]
  },
  {
   "title": "Frequencies - 5s - P95 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(audio_spectrum_value_bucket{job=\"audio\"}[1m]))",
     "legendFormat": "{{frequency}}Hz"
    }
   ]
  },
  {
   "title": "Frequencies - 15s - P75 rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(audio_spectrum_value_bucket{job=\"audio\"}[$__rate_interval]))",
     "legendFormat": "{{frequency}}Hz"
    }
   ]
  },
  {
   "title": "Process Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process memory consumption",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "delta(process_resident_memory_bytes{job=\"audio\"}[$__interval])",
       "legendFormat": "delta"
      },
      {
       "expr": "rate(process_resident_memory_bytes{job=\"audio\"}[$__rate_interval])",
       "legendFormat": "resident_memory"
      }
     ]
    },
    {
     "title": "Process memory - stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_stack_inuse_bytes{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "stack_in_use"
      },
      {
       "expr": "rate(go_memstats_mspan_inuse_bytes{job=\"audio\"}[$__interval])",
       "legendFormat": "mspan_in_use"
      },
      {
       "expr": "rate(go_memstats_sys_bytes{job=\"audio\"}[$__interval])",
       "legendFormat": "sys"
      }
     ]
    },
    {
     "title": "Process memory - garbage collection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds{job=\"audio\"}[$__rate_interval])",
       "legendFormat": "P{{quantile}}"
      }
     ]
    },
    {
     "title": "Process memory - heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "alloc_total"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "heap_alloc"
      },
      {
       "expr": "rate(go_memstats_heap_idle_bytes{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "heap_idle"
      },
      {
       "expr": "rate(go_memstats_heap_inuse_bytes{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "heap_in_use"
      },
      {
       "expr": "rate(go_memstats_heap_sys_bytes{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "heap_sys"
      },
      {
       "expr": "rate(go_memstats_next_gc_bytes{job=\"audio\", instance=\"192.168.10.7:13088\"}[$__interval])",
       "legendFormat": "next_gc"
      }
     ]
    }
   ]
  }
 ]
}