version: '3.7'
services:

  secr:
    build:
      context: . 
      dockerfile: ./Dockerfile
    container_name: secr
    ports: 
      - 8080:8080
    restart: unless-stopped
    volumes:
      - /tmp/secr:/secr